[keys]
prefix = "ctrl+q"
settings = ""
detach = "prefix+d"
goto = "prefix+s"
rename_workspace = "prefix+$"
rename_tab = "prefix+,"
split_vertical = "prefix+%"
split_horizontal = "prefix+\""
zoom = "prefix+z"       # legacy alias: fullscreen
navigate_workspace_up = "k"
navigate_workspace_down = "j"
