[general]
import = [
  "/home/ison/.config/alacritty/font.toml",
  "/home/ison/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "C", mods="Control|Shift", action="Copy"},
  { key = "V", mods="Control|Shift", action="Paste"}
]
[window]
padding = { x = 10, y = 10 }
startup_mode = 'Maximized'
dynamic_title = false
decorations = 'None'

