#!/bin/bash

# intent for bash and zsh balance
SHELL_ROOT=$(dirname ${BASH_SOURCE:-$0})

export PATH=$PATH:$HOME/.local/bin

source $SHELL_ROOT/alias

function lfc () {
  cd "$(command lf -print-last-dir "$@")"
}

# fzf config
export FZF_DEFAULT_COMMAND='fd --type f --color=never'
export FZF_DEFAULT_OPTS='--no-height --cycle --reverse'

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :50 {}'"

export FZF_ALT_C_COMMAND='fd --type d . --color=never --hidden'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -50'"
