function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
  endif
endfunction

call SourceIfExists("~/.vim/plugin.vim")

call SourceIfExists("~/.vim/core")
"============ Some vim 9 feature ==============

call SourceIfExists("~/.vim/fzf.vim")
call SourceIfExists("~/.vim/git.vim")
"" local config for override
call SourceIfExists("~/.vim/local.vim")
