function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
  endif
endfunction

let g:ranger_map_keys = 0

call SourceIfExists("~/.vim/plugin.vim")

call SourceIfExists("~/.vim/core")
"============ Some vim 9 feature ==============

call SourceIfExists("~/.vim/fzf.vim")
call SourceIfExists("~/.vim/git.vim")
call SourceIfExists("~/.vim/ranger.vim")

colorscheme nord

"" local config for override
call SourceIfExists("~/.vim/local.vim")

