#!/usr/bin/env bash

download() {
  grim -g "$(slurp)" $(xdg-user-dir PICTURES)/$(date +'%s_grim.png')
}

clipboard() {
 grim -g "$(slurp)" - | wl-copy
}

screen() {
 grim - | wl-copy
}

case $1 in
  clipboard|download|screen)
   $1 $@;;
  usage)
   $0 $(echo -e "clipboard\ndownload\nscreen" | fuzzel --dmenu);;
 * )
   exit 0;;
esac

