#!/usr/bin/env bash

if [ $1 == "otp" ]; then
  pass_cmd=otp
  prompt=Otp
elif [ $1 == "password" ]; then
  pass_cmd=show
  prompt=Password
else
  exit 0
fi

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

xdotool="xdotool type --clearmodifiers --file -"

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu)


[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass $pass_cmd -c "$password" 2>/dev/null
else
	pass $pass_cmd "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi

