#!/bin/bash
# if in wayland tool is fuzzel
if [[ -n $WAYLAND_DISPLAY ]]; then
  tool="fuzzel --dmenu"
# if in x11 tool is rofi -dmenu
elif [[ -n $XDG_SESSION_TYPE ]]; then
  tool="rofi -dmenu"
fi

# intent for bash and zsh balance
SHELL_ROOT=$(dirname ${BASH_SOURCE:-$0})

HANDLER="$SHELL_ROOT/workflow_handler"


function main() {
  menu=(
    "clipboard"
    "goldendict"
    "grim"
    "password"
    "otp"
  )
  $HANDLER $(printf "%s\n" "${menu[@]}" | $tool)
}

main "$@"
