#!/bin/bash

# if in wayland tool is fuzzel
if [[ -n $WAYLAND_DISPLAY ]]; then
  tool="fuzzel --dmenu"
# if in x11 tool is rofi -dmenu
elif [[ -n $XDG_SESSION_TYPE ]]; then
  tool="rofi -dmenu"
fi

# intent for bash and zsh balance
SHELL_ROOT=$(dirname ${BASH_SOURCE:-$0})

function main() {
  if [[ $# -lt 1 ]]; then
    exit 0
  else
    option=$1
    case $option in
      "goldendict")
        $SHELL_ROOT/goldendict
        ;;
      "password")
        $SHELL_ROOT/passmenu password
        ;;
      "otp")
        $SHELL_ROOT/passmenu otp
        ;;
      "clipboard")
        cliphist list | fuzzel --dmenu | cliphist decode | wl-copy
        ;;
      "grim")
        $SHELL_ROOT/grim usage
        ;;
      "exit") ;;
    esac
  fi

}

main "$@"
